schoolstore/schoolstoreproject/schoolstoreproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('storeapp.urls')),
    path('', include('credentials.urls')),
    path('department/', include('department.urls')),




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

schoolstore/schoolstoreproject/storeapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('add',views.Orderview.as_view(),name="add"),
    path('', views.demo,name='demo'),
    path('home',views.home,name='home'),
    path('ajax/load-courses/',views.load_courses, name='ajax_load_courses'),
    # path('order',views.add_order,name='order'),
    # path('ajax/load_courses/', views.load_courses, name='ajax_load_courses'),
    # path('orders',views.update,name="don")

    ]

schoolstore/schoolstoreproject/storeapp/models.py
from django.db import models
from department.models import Department, Course


# Create your models here.
class Purpose(models.Model):
    purpose = models.CharField(max_length=250)

    def __str__(self):
        return self.purpose


class Materials(models.Model):
    material = models.CharField(max_length=100)

    def __str__(self):
        return self.material


class Order(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField()
    age = models.IntegerField()
    options=(
        ('male','male'),
        ('female','female')
    )
    gender = models.CharField(max_length=200,choices=options,default='male')
    phonenumber = models.CharField(max_length=10)
    mailid = models.EmailField(max_length=100)
    address = models.CharField(max_length=250)
    deptname = models.ForeignKey(Department,  on_delete=models.SET_NULL, null=True)
    course = models.ForeignKey(Course,  on_delete=models.SET_NULL, null=True)
    purpose = models.ForeignKey(Purpose, on_delete=models.CASCADE)
    materials = models.ManyToManyField(Materials)

    # class Meta:
    #     db_table = 'Order'

    def __str__(self):
        return self.name

schoolstore/schoolstoreproject/templates/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Freelancer - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top">College Store</a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">

                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                     href="#">Hii {{user.username}}</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                     href="logout">Logout</a></li>


            </ul>
        </div>
    </div>
</nav>

<section class="page-section portfolio" id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Fill the form!</p>
                        <div class="divider-custom">
                            <div class="row">
                                <div class="col-12">
                                    <form action="" method="post" enctype="multipart/form-data" id="personForm"
                                          data-courses-url="{% url 'ajax_load_courses' %}" novalidate>
                                        {%csrf_token%}
                                        {{form.as_p}}
                                        <div class="d-grid">
                                            <button class="btn btn-primary btn-login text-uppercase fw-bold"
                                                    type="submit">submit
                                            </button>
                                        </div>
                                    </form>
                                    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                                    <script>
                                            $("#id_deptname").change(function () {
                                              const url = $("#personForm").attr("data-courses-url");
                                              const deptnameId = $(this).val();

                                              $.ajax({
                                                url: url,
                                                data: {
                                                  'deptname_id': deptnameId
                                                },
                                                success: function (data) {
                                                  $("#id_cname").empty();
                                                  for (let i = 0; i < data.courses.length; i++) {
                                                            var option = $('<option/>');
                                                            option.attr({ 'value': data.courses[i].id }).text(data.courses[i].name);
                                                            $('#id_course').append(option);
                                                        }
                                                }
                                              });

                                            });

                                    </script>

                                </div>
                            </div>
                        </div><!-- Portfolio Grid Items-->

                    </div>
                    {% for m in messages %}
                    <h2>{{m}}</h2>
                    <button class="btn btn-primary btn-login text-uppercase fw-bold"
                            type="button"><a href="home">submit</a>
                    </button>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>




</section>

<!-- Copyright Section-->
<div class="copyright py-4 text-center text-white">
    <div class="container"><small>Copyright &copy; Your Website 2023</small></div>
</div>
<!-- Portfolio Modals-->
<!-- Portfolio Modal 1-->


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<script src="{% static 'js/scripts.js' %}"></script>

<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

schoolstore/schoolstoreproject/templates/drop.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ c.pk }}">{{course.name }}</option>
{% endfor %}

schoolstore/schoolstoreproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>




<body>

  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card border-0 shadow rounded-3 my-5">
          <div class="card-body p-4 p-sm-5">
            <h5 class="card-title text-center mb-5 fw-light fs-5">Sign In</h5>
            <form action="login" method="post">
                 {% csrf_token %}
              <div class="form-floating mb-3">
                 <input type="text"  class="form-control" name="username" />
                      <label class="form-label" >Username</label>
              </div>
              <div class="form-floating mb-3">
                 <input type="password"  class="form-control" name="password" />
                      <label class="form-label" >Password</label>
              </div>


              <div class="d-grid">
                <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">Sign
                  in</button>
              </div>


            </form>

          </div>
        </div>
              {% for m in messages %}
              <h2>{{m}}</h2>

            {% endfor %}
      </div>
    </div>
  </div>
</body>

schoolstore/schoolstoreproject/templates/order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Freelancer - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top">College Store</a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">

                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                     href="#">Hii {{user.username}}</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                                     href="logout">Logout</a></li>


            </ul>
        </div>
    </div>
</nav>

<section class="page-section portfolio" id="portfolio">
    <div class="container">
        <!-- Portfolio Section Heading-->

        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><a class="btn btn-primary" href="/add" role="button">click here</a></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Portfolio Grid Items-->

    </div>
</section>

<!-- Copyright Section-->
<div class="copyright py-4 text-center text-white">
    <div class="container"><small>Copyright &copy; Your Website 2023</small></div>
</div>
<!-- Portfolio Modals-->
<!-- Portfolio Modal 1-->



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<script src="{% static 'js/scripts.js' %}"></script>

<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

schoolstore/schoolstoreproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>

<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">


                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Register</p>
                                <div class="container">
                                    <div class="row">
                                        <div class="col-4"></div>
                                        <div class="col-4">
                                            {%if messages%}
                                            {%for m in messages%}
                                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                <strong>Holy guacamole!</strong> {{m}}
                                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                                        aria-label="Close"></button>
                                            </div>
                                            {%endfor%}
                                            {%endif%}
                                        </div>
                                        <div class="col-4">

                                        </div>
                                    </div>
                                </div>

                                <div class="container">
                                    <div class="row">
                                        <div class="col-4"></div>
                                        <div class="col-4">
                                            <form action="" method="post" enctype="multipart/form-data">
                                                {%csrf_token%}
                                                {{form.as_p}}

                                                <button type="submit" class="btn btn-info">Register</button>
                                            </form>
                                        </div>
                                        <div class="col-4"></div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    </div>
</section>


</body>
</html>